net: add optional ?sw argument to with_tcp_connect
ocaml-multicore/eio pull request #425
Opened 2023-01-30 13:37 UTC by bikallem

Part of the fix for https://github.com/mirage/ocaml-cohttp/issues/965. 

After this is merged Client.call should take an (optional? not decided yet) sw argument too.

2023-01-30 13:37 UTC, bikallem commented
/cc @talex5

2023-01-30 14:05 UTC, talex5 requested changes
The point of the `with_*` functions is that you don't need a switch. It would be better to have a separate `tcp_connect` that takes `~sw` and doesn't take `f` if you need that.

2023-01-31 10:00 UTC, bikallem commented
@talex5 I have added new function `tcp_connect` as you suggested. This takes switch as an argument so the connection outlives the function call. 

ci seems to be failing due to an error below.
```
2023-01-31 09:30.50: Waiting for resource in pool OCluster

2023-01-31 09:30.50: Waiting for worker…

2023-01-31 09:30.50: Got resource from pool OCluster

Building on cree.ocamllabs.io

Uncaught exception: Unix.Unix_error(Unix.ENOMEM, "fork", "")

2023-01-31 09:30.51: Job failed: Failed: Internal error
```

2023-03-24 23:39 UTC, bikallem commented
closing this for now.

2023-03-24 23:39 UTC, closed without merging